version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
  web:
    build: 
      context: .
      args:
        # todo: make this dynamic
        USERID: 1000
        GROUPID: 1000
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
    depends_on:
      - db

volumes:
  pgdata: