version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
      args:
        # todo: make this dynamic
        USERID: 1000
        GROUPID: 1000
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "${API_PORT}:8002"
    depends_on:
      - db
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
      args:
        # todo: make this dynamic
        USERID: 1000
        GROUPID: 1000
    command: npm start
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - "${WEB_PORT}:8003"
    env_file:
      - ./.env
    depends_on:
      - api

volumes:
  pgdata:
