version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
      args:
        # todo: make this dynamic
        USERID: 1000
        GROUPID: 1000
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
    depends_on:
      - db
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
      args:
        # todo: make this dynamic
        USERID: 1000
        GROUPID: 1000
    command: npm start
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - "8003:8003"
    environment:
      - EXPRESS_SECRET=${EXPRESS_SECRET}
      - CLOUDFRONT_URL=${CLOUDFRONT_URL}
      - S3_LOCATION=${S3_LOCATION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - api

volumes:
  pgdata:
