# Generated by Django 3.2.13 on 2022-06-05 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20220605_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Chef_Settings',
        ),
    ]
