# Generated by Django 3.2.13 on 2022-06-05 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_rename_settings_chef_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef_settings',
            name='id',
        ),
        migrations.AlterField(
            model_name='chef_settings',
            name='chef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
